import './globals.css'
import { Inter } from 'next/font/google'
import ApolloWrapper from '@/lib/apollo-wrapper';
import ReduxProvider from '@/features/Provider';
import Cookies from 'js-cookie';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Admin Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <ApolloWrapper>

        {children}
        </ApolloWrapper>

        </ReduxProvider>
        </body>
    </html>
  )
}
