
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Customer Portal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
const navAndFotterHidingRoute = ["/dashboard"];
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar navAndFotterHidingRoute={navAndFotterHidingRoute}/>
        {children}
        <Footer navAndFotterHidingRoute={navAndFotterHidingRoute}/>
      </body>
    </html>
  );
}
