
import './globals.css';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ReduxProvider from '@/features/Provider';

const popin = Poppins({
   weight: ["200", "400", "500"],
   subsets: ['latin'],
  });

export const metadata = {
  title: 'Customer Portal',
  description: 'Generated by create next app',
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
const navAndFotterHidingRoute = ["/dashboard"];
  

  return (
    <html lang="en">
      <body className={popin.className}>
        <Navbar navAndFotterHidingRoute={navAndFotterHidingRoute}/>
        <ReduxProvider>
          {children}
        </ReduxProvider>
        <Footer navAndFotterHidingRoute={navAndFotterHidingRoute}/>
      </body>
    </html>
  );
}
